version: 3.2.{build}
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
after_build:
- ps: dotnet pack /p:Version=$env:APPVEYOR_BUILD_VERSION src\Elmah.Io.Extensions.Logging\Elmah.Io.Extensions.Logging.csproj --output artifacts
test: off
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: F5CTc3/bSmMHKRW3d4pOSQu5roNE4RNb4wspqcdWDt8nCd3x2hR7nDAYEywofdn+